---
language: go
dist: trusty
sudo: required

go:
  - 1.9
#  - master

env:
  global:
    - CGO_CFLAGS=-I/usr/local/include
    - CGO_LDFLAGS=-L/usr/local/lib

before_install:
- apt-get install libgpgme-dev

install:
- true #do not execute "go get ./..." as it will fail with the examples

script:
  - go test -v .
